"""empty message

Revision ID: 9217ea1c9d40
Revises: 
Create Date: 2017-11-30 20:09:24.506611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9217ea1c9d40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('EID', sa.String(length=20), nullable=False),
    sa.Column('Ename', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('job', sa.String(length=20), nullable=False),
    sa.Column('basicWage', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('EID')
    )
    op.create_table('check',
    sa.Column('CID', sa.Integer(), nullable=False),
    sa.Column('lateTimes', sa.String(length=20), nullable=False),
    sa.Column('earlyTimes', sa.String(length=20), nullable=False),
    sa.Column('leaveTimes', sa.String(length=20), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('EID', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['EID'], ['employee.EID'], ),
    sa.PrimaryKeyConstraint('CID')
    )
    op.create_table('feedback',
    sa.Column('FID', sa.Integer(), nullable=False),
    sa.Column('feedText', sa.Text(), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('EID', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['EID'], ['employee.EID'], ),
    sa.PrimaryKeyConstraint('FID')
    )
    op.create_table('wage',
    sa.Column('WID', sa.Integer(), nullable=False),
    sa.Column('basicWage', sa.Integer(), nullable=False),
    sa.Column('checkWage', sa.Integer(), nullable=False),
    sa.Column('overTimeWage', sa.Integer(), nullable=False),
    sa.Column('realWage', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('EID', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['EID'], ['employee.EID'], ),
    sa.PrimaryKeyConstraint('WID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wage')
    op.drop_table('feedback')
    op.drop_table('check')
    op.drop_table('employee')
    # ### end Alembic commands ###
