"""empty message

Revision ID: c84227d6bdb9
Revises: 9217ea1c9d40
Create Date: 2017-11-30 20:12:15.825410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c84227d6bdb9'
down_revision = '9217ea1c9d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_table',
    sa.Column('CID', sa.Integer(), nullable=False),
    sa.Column('lateTimes', sa.String(length=20), nullable=False),
    sa.Column('earlyTimes', sa.String(length=20), nullable=False),
    sa.Column('leaveTimes', sa.String(length=20), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('EID', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['EID'], ['employee.EID'], ),
    sa.PrimaryKeyConstraint('CID')
    )
    op.drop_table('check')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check',
    sa.Column('CID', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('lateTimes', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('earlyTimes', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('leaveTimes', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('date', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('EID', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['EID'], ['employee.EID'], name='check_ibfk_1'),
    sa.PrimaryKeyConstraint('CID'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('check_table')
    # ### end Alembic commands ###
